// screens data
const SCREENS = [
  [1,'index（ホーム画面）','画面','プロフィール情報表示','','/'],
  [2,'','','店舗一覧表示','',''],
  [3,'','','日時選択','',''],
  [4,'','','絞り込み検索','ドロップダウン 16 個・チェックボックス 20 個が 1 画面に集中しており、初回ユーザーには操作が複雑に感じられる可能性がある',''],
  [5,'','','複数条件選択','',''],
  [6,'','','料金計算・表示','料金計算結果がどのタイミングで更新されるか（リアルタイムか送信後か）がユーザーに伝わりにくい',''],
  [7,'','','予約状況確認','',''],
  [8,'','','確認ダイアログ','',''],
  [9,'','','店舗画像表示','',''],
  [10,'','','HTMLコンテンツ表示','',''],
  [11,'','','進捗バー表示','ワークフローが 180 本と突出して多く、画面の責務が過大。機能ごとにページ分割またはリユーザブル要素への切り出しを検討\n要素数 33・ワークフロー 180 本の複雑な構成はパフォーマンス低下の原因になりやすい。初期描画の遅延計測を推奨',''],
  [12,'search（検索画面）','画面','店舗検索','ページタイトル・meta description 未設定のため、検索エンジンからの流入が期待できない','/search'],
  [13,'','','検索結果一覧表示','検索結果が 0 件の場合のエンプティステートが未定義',''],
  [14,'','','検索フィルター','検索フィルターの適用状態（何件絞り込まれているか）をユーザーに視覚的にフィードバックする仕組みがない',''],
  [15,'','','画像ギャラリー表示','',''],
  [16,'','','絞り込みアクション','',''],
  [17,'','','ヘッダー表示','',''],
  [18,'shop_detail（店舗詳細画面）','画面','店舗基本情報表示','OGP 未設定のため、SNS でシェアしても店舗名・画像が表示されない','/shop_detail'],
  [19,'','','営業時間・定休日表示','',''],
  [20,'','','料金メニュー表示','',''],
  [21,'','','地図表示','Google Map の表示が CDN 障害・ネットワーク制限の影響を受けやすく、位置情報が確認できなくなるケースがある',''],
  [22,'','','空き状況確認','',''],
  [23,'','','日付・時間帯選択','',''],
  [24,'','','台数・数量選択','',''],
  [25,'','','オプション選択','',''],
  [26,'','','予約操作','予約データ作成ワークフローに対して、二重送信防止（Idempotency）の仕組みが確認できない',''],
  [27,'','','写真ギャラリー','',''],
  [28,'','','備考入力','',''],
  [29,'','','予約確認ダイアログ','予約確認ダイアログ（ポップアップ）が 2 個あり、ユーザーが予約完了までのステップ数を把握しにくい',''],
  [30,'','','外部リンク','',''],
  [31,'user_reservation_list（予約一覧画面）','画面','予約一覧表示','予約が 0 件の場合のエンプティステートが未定義\n過去・今後の予約が同一リストで表示される場合、視覚的な区別が不明瞭になる可能性がある','/user_reservation_list'],
  [32,'','','予約状態管理','',''],
  [33,'','','予約詳細確認','',''],
  [34,'','','予約キャンセル','E2Eテストにて「予約をキャンセルする」ボタン押下後に確認ダイアログ（「はい」「OK」等）が検出されず、予約件数も変化しなかった。キャンセル前の確認ステップが欠如しているか、キャンセルフローが正常に完了していない可能性がある',''],
  [35,'','','詳細ポップアップ','',''],
  [36,'','','予約履歴表示','認証が必要なページだが、未ログイン時のリダイレクト処理・エラー表示の挙動が明示されていない',''],
  [37,'shop_form（店舗フォーム画面）','画面','店舗情報入力','必須項目の明示（アスタリスク等）がない可能性がある','/shop_form'],
  [38,'','','カテゴリ選択','',''],
  [39,'','','説明文入力','入力バリデーションがクライアントサイドで確認できず、不完全なデータが登録される可能性がある',''],
  [40,'','','フォーム送信','フォーム送信後の成功フィードバック（完了メッセージ・遷移先）が不明確',''],
  [41,'','','キャンセル操作','',''],
  [42,'','','送信確認ダイアログ','',''],
  [43,'shop_term（店舗規約画面）','画面','規約テキスト表示','','/shop_term'],
  [44,'','','静的コンテンツ表示','',''],
  [45,'reset_pw（パスワードリセット画面）','画面','メールアドレス入力','','/reset_pw'],
  [46,'','','新パスワード入力','パスワード強度の要件（文字数・使用可能文字等）がユーザーに提示されていない可能性がある',''],
  [47,'','','パスワード変更送信','リセット完了後の導線（ログイン画面への遷移等）が不明確\nパスワードリセットトークンの有効期限・使い捨て制御が Bubble 標準機能に依存しており、カスタム制御が困難',''],
  [48,'','','エラーメッセージ表示','',''],
  [49,'404（エラー画面）','画面','エラーメッセージ表示','','/404'],
  [50,'','','ホームへ戻るリンク','',''],
  [51,'admin（管理者ダッシュボード）','画面','売上・レポート表示','admin・shop_admin ページへのアクセスはロールチェックで保護されているが、URL 直打ちによる不正アクセスへの対策が明示されていない','/admin'],
  [52,'','','ユーザー管理','',''],
  [53,'','','店舗管理','',''],
  [54,'','','予約管理','',''],
  [55,'','','データ一覧表示','大量データを扱うリスト（19〜28 リスト）でページネーションや遅延読み込みが適切に設定されているか確認が必要',''],
  [56,'','','フィルター・検索','',''],
  [57,'','','条件絞り込み','',''],
  [58,'','','詳細情報ポップアップ','1 画面に多数の操作（ポップアップ 19〜26 個）が集中しており、管理者の学習コストが高い',''],
  [59,'','','データ操作','データの削除操作に対して論理削除・削除確認・操作ログの仕組みが確認できない',''],
  [60,'','','期間指定','',''],
  [61,'','','データエクスポート','CSV エクスポート等の操作後の完了フィードバックが不明確',''],
  [62,'','','アラート・通知','',''],
  [63,'admin_login（管理者ログイン画面）','画面','メールアドレス入力','','/admin_login'],
  [64,'','','パスワード入力','ブルートフォース攻撃に対するレート制限・アカウントロック機能が確認できない',''],
  [65,'','','ログイン実行','HTTPS 通信は確認できるが、CSRF トークンによる二重送信防止が Bubble 標準外の管理画面で機能しているか不明',''],
  [66,'','','エラーメッセージ表示','ログイン失敗時のエラーメッセージがポップアップ表示のみで、フォームのどの入力が誤りかが伝わりにくい',''],
  [67,'admin_price_simulation（料金シミュレーション画面）','画面','売上グラフ表示','','/admin_price_simulation'],
  [68,'','','料金シミュレーション','',''],
  [69,'','','対象期間選択','',''],
  [70,'admin_update_calendar（カレンダー管理画面）','画面','営業日・定休日設定','','/admin_update_calendar'],
  [71,'','','日付選択','',''],
  [72,'','','設定の保存','',''],
  [73,'shop_admin（店舗管理者ダッシュボード）','画面','売上・レポート表示','admin・shop_admin ページへのアクセスはロールチェックで保護されているが、URL 直打ちによる不正アクセスへの対策が明示されていない','/shop_admin'],
  [74,'','','予約管理','',''],
  [75,'','','ユーザー情報確認','',''],
  [76,'','','料金・メニュー管理','',''],
  [77,'','','カレンダー管理','',''],
  [78,'','','データ一覧表示','大量データを扱うリスト（19〜28 リスト）でページネーションや遅延読み込みが適切に設定されているか確認が必要',''],
  [79,'','','フィルター・検索','',''],
  [80,'','','条件絞り込み','',''],
  [81,'','','詳細情報ポップアップ','1 画面に多数の操作（ポップアップ 19〜26 個）が集中しており、管理者の学習コストが高い',''],
  [82,'','','データ操作','データの削除操作に対して論理削除・削除確認・操作ログの仕組みが確認できない',''],
  [83,'','','日程指定','',''],
  [84,'','','複数選択','',''],
  [85,'','','データエクスポート','CSV エクスポート等の操作後の完了フィードバックが不明確',''],
  [86,'','','アラート・通知','',''],
  [87,'shop_admin_login（店舗管理者ログイン画面）','画面','メールアドレス入力','','/shop_admin_login'],
  [88,'','','パスワード入力','ブルートフォース攻撃に対するレート制限・アカウントロック機能が確認できない',''],
  [89,'','','ログイン実行','HTTPS 通信は確認できるが、CSRF トークンによる二重送信防止が Bubble 標準外の管理画面で機能しているか不明',''],
  [90,'','','エラーメッセージ表示','ログイン失敗時のエラーメッセージがポップアップ表示のみで、フォームのどの入力が誤りかが伝わりにくい',''],
  [91,'index（検索結果・top_search）','画面状態（index 内）','ログイン後の自転車検索ホーム表示','','/index/top_search'],
  [92,'','','エリア・日時・自転車種類の絞り込み検索','自転車種類フィルタ（ロードバイク等）を選択して検索した際に結果が表示されないケースをE2Eテストで確認。フィルター適用後の件数フィードバックが不明確',''],
  [93,'','','貸出可能な自転車の一覧表示','',''],
  [94,'','','新着情報（お知らせ）の一覧表示','',''],
  [95,'','','TOPICSコンテンツの一覧表示','',''],
  [96,'','','よくある質問（アコーディオン）','',''],
  [97,'index（マイページ）','画面状態（index 内）','ユーザー情報の表示（氏名・電話番号・住所・生年月日・身長・メールアドレス）','','/index/mypage'],
  [98,'','','アカウント編集ページへの導線','',''],
  [99,'','','予約一覧ページへの導線','',''],
  [100,'','','退会機能','退会フローの確認ステップ・完了後の導線が不明確',''],
  [101,'index（アカウント情報編集）','画面状態（index 内）','氏名・電話番号・住所・生年月日・身長等の編集フォーム','必須項目の明示がない可能性がある\n変更完了後のフィードバック（完了メッセージ・遷移先）が不明確','/index/edit'],
  [102,'','','郵便番号からの住所自動入力（「住所に反映」ボタン）','',''],
  [103,'','','メールマガジン受信設定（チェックボックス）','',''],
  [104,'index（ご利用ガイド）','画面状態（index 内）','ご利用方法の静的コンテンツ表示','','/index/guide'],
  [105,'index（料金・支払い方法）','画面状態（index 内）','料金プランの静的コンテンツ表示','','/index/howtopay'],
  [106,'','','「予約を確定する」ボタン（予約フローへの誘導）','',''],
  [107,'index（自転車詳細・予約フォーム）','画面状態（index 内）','自転車の基本情報・画像表示','','/index/bicycle_detail'],
  [108,'','','貸出日・返却日の日付選択（Pikadayカレンダー）','「予約画面へ進む」ボタンがBubble内部の button_disabled プリコンピュートキャッシュにより、日時選択完了後もクリックを受け付けないケースがある。通常のクリックでワークフローが発火しないため操作不能に見える',''],
  [109,'','','貸出時間・返却時間の選択（日付選択後に動的生成されるSELECTボックス）','',''],
  [110,'','','予約画面へ進む（カートへ遷移）','',''],
  [111,'index（カート・予約確認フロー）','画面状態（index 内）','予約内容（自転車・日時・料金）の確認表示','','/index/cart'],
  [112,'','','お客様情報の入力','',''],
  [113,'','','予約内容の最終確認画面への遷移','',''],
  [114,'','','予約確定処理（完了後 /index/top_search へリダイレクト）','予約データ作成に対して二重送信防止（Idempotency）の仕組みが確認できない',''],
  [115,'index（新着情報詳細）','画面状態（index 内）','新着情報・お知らせのコンテンツ表示','','/index/news_detail?news={id}'],
  [116,'','','一覧へ戻るナビゲーション（/?back=news_pc へ遷移）','',''],
  [117,'index（TOPICSコンテンツ詳細）','画面状態（index 内）','トピックス記事のコンテンツ表示','','/index/topics_detail?banner={id}'],
  [118,'','','一覧へ戻るナビゲーション','',''],
  [119,'index（よくある質問）','画面状態（index 内）','FAQの静的コンテンツ表示','','/index/faq'],
  [120,'index（プライバシーポリシー）','画面状態（index 内）','プライバシーポリシーの静的コンテンツ表示','','/index/privacypolicy'],
  [121,'index（お問い合わせ）','画面状態（index 内）','お問い合わせフォーム（メールアドレス・メッセージ入力）','送信後の完了メッセージ・遷移先が不明確\n入力バリデーションがクライアントサイドで確認できない','/index/contact'],
  [122,'','','送信処理','',''],
];

const EMAILS = [
  [1, '実装済','メールアドレス確認メール','新規会員登録したとき','ユーザー','【Rincle】メールアドレスのご確認','Rincleをご利用いただきありがとうございます。\n\n以下の6桁の確認コードを登録画面にご入力ください。\n\n🔒 確認コード：{確認コード}\n\n※コードを他人と共有しないようご注意ください。\n\nご不明点がございましたら、お気軽にお問い合わせください。'],
  [2, '実装済','アカウント登録完了メール','会員登録完了したとき','ユーザー','【Rincle】アカウント登録完了','{氏名}様\n\nこの度はRincleにご登録いただき、誠にありがとうございます。\nアカウントの登録が正常に完了しましたので、お知らせいたします。\n\n━━━━━━━━━━━━━━━━━━━━\n■登録情報\n・ユーザー名：{氏名}\n・登録メールアドレス：{メールアドレス}\n━━━━━━━━━━━━━━━━━━━━\n\nご登録いただいたアカウントで、すぐにサービスをご利用いただけます。\nログインはこちらから：{ログインURL}'],
  [3, '実装済','パスワード再設定メール','パスワード変更申請したとき','ユーザー','Rincle｜パスワード再設定','RINCLEのパスワード変更のリクエストを受けました。\nもしあなたがこのリクエストを送信していない場合、このeメールは無視してください。もしお送りいただいているのなら、下のリンクからあなたのログイン情報を変更できます。\n\n{パスワードリセットURL}'],
  [4, '協議中','新メールアドレス確認メール','メールアドレス変更申請したとき','ユーザー','【重要】メールアドレス変更のお知らせ','メールアドレス再設定リクエストを受け付けました。\n下記URLから新メールアドレスの認証を行ってください。\n\n▼メールアドレス認証はこちら\n{認証URL}\n\n※このリンクの有効期限は24時間です。'],
  [5, '実装済','予約確定メール','予約確定したとき','ユーザー','【Rincle】ご予約の確認','この度はRINCLEをご利用いただき、誠にありがとうございます。\n以下の内容でご予約が確定いたしました。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【ご予約内容】\n■予約番号：#{予約番号}\n■ご利用日：{貸出日時}\n■返却予定日時：{返却日時}\n■ご利用店舗：{店舗名}\n　Googleマップ：{マップURL}\n■ご利用バイク：{バイク情報}\n\n【レンタル料金】\n■基本料金：¥{料金}\n■合計金額：¥{合計}'],
  [6, '実装済','予約キャンセル通知メール','予約キャンセルしたとき','ユーザー','【Rincle】ご予約のキャンセル','この度はRINCLEをご利用いただき、誠にありがとうございます。\n以下の予約がキャンセルされました。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【ご予約内容】\n■予約番号：#{予約番号}\n■キャンセル日：{キャンセル日}\n■ご利用予定日：{貸出日時}\n■返却予定日時：{返却日時}\n■ご利用店舗：{店舗名}\n■ご利用バイク：{バイク情報}\n\n【レンタル料金】\n■基本料金：¥{料金}\n■合計金額：¥{合計}'],
  [7, '協議中','決済失敗通知メール','決済失敗したとき','ユーザー','【重要】お支払いに失敗しました','お客様のご予約に際し、お支払い処理に失敗いたしました。\n\nお手数ですが、カード情報をご確認のうえ、再度お試しいただくか、別のカードをご利用ください。\n\n予約を続ける場合はこちら：{予約URL}\n\n※ご不明点はお問い合わせください。'],
  [8, '実装済','お問い合わせ受付メール','お問い合わせ送信したとき','ユーザー','（RINCLE）お問い合わせを受け付けました','{氏名}様\n\nこのたびはRINCLEへお問い合わせいただき、誠にありがとうございます。\n以下の内容でお問い合わせを受け付けました。担当者より改めてご連絡いたします。\n\n―― お問い合わせ内容の控え ――\n【お問い合わせ種別】{種別}\n【お名前】{氏名}\n【メール】{メールアドレス}\n【お問い合わせ内容】\n{内容}\n\n※ご入力いただいたメールアドレスに誤りがないかご確認ください。'],
  [9, '協議中','退会完了メール','退会手続き完了したとき','ユーザー','【重要】退会手続き完了のお知らせ','この度はRINCLEをご利用いただき、誠にありがとうございました。\n\nご退会の手続きが完了しましたことをお知らせいたします。\nこれまでのご利用に感謝申し上げます。\n\n※退会後はログインできなくなります。\n※ご予約データは一定期間保持されます。'],
  [10,'実装済','加盟店申請案内メール','管理者が店舗候補に招待時','店舗','Rincle｜加盟店申請のご案内','お世話になっております、Rincle運営です。\n\n以下のURLより加盟店情報のご登録と、クレジットカードの利用申請をよろしくお願いいたします。\n\n{shop_formURL}'],
  [11,'実装済','審査通過通知メール','Pay.JP審査通過時','店舗','審査通過のご案内','{担当者名}様\n\n決済サービス側での審査が通過しましたことをお知らせいたします。\n\n以下のページからログインを行い、詳細な店舗情報の登録にお進みください。\n{shop_admin_loginURL}'],
  [12,'実装済','審査否決通知メール','Pay.JP審査否決時','店舗','審査否決のご案内','{担当者名}様\n\n決済サービス側での審査が却下されましたことをお知らせいたします。'],
  [13,'実装済','予約確定通知メール','予約確定したとき','店舗','【Rincle】新規ご予約','{店舗名} ご担当者様\n\n以下の通り、RINCLEよりご予約が確定しましたのでご案内いたします。\nご来店準備・レンタルバイクのご用意をお願いいたします。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【ご予約内容】\n■予約番号：#{予約番号}\n■貸出予定日時：{貸出日時}\n■返却予定日時：{返却日時}\n■ご利用バイク・ご利用者情報：{バイク情報}\n\n【レンタル料金】\n■合計金額：¥{合計}'],
  [14,'実装済','予約キャンセル通知メール','予約キャンセルしたとき','店舗','【Rincle】ご予約のキャンセル','{店舗名} ご担当者様\n\n下記のご予約がユーザー様によりキャンセルされましたので、ご確認と対応をお願いいたします。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【キャンセル内容】\n■予約番号：#{予約番号}\n■キャンセル日：{キャンセル日}\n■ご利用予定日：{貸出日時}\n■返却予定日時：{返却日時}\n■ご利用バイク：{バイク情報}\n\n【レンタル料金】\n■合計金額：¥{合計}'],
  [15,'実装済','お問い合わせ転送メール','店舗宛お問い合わせ受信時','店舗','（RINCLE_HPお問い合わせ）{種別}','平素よりRINCLEにご協力いただき、誠にありがとうございます。\n本メールは、RINCLE公式サイトのお問い合わせフォームより、貴販売店様宛に寄せられた内容を転送しております。\n\nお客様へのご対応をよろしくお願いいたします。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【お問い合わせ種別】{種別}\n【お名前】{氏名}\n【メール】{メールアドレス}\n【お問い合わせ内容】\n{内容}\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝'],
  [16,'実装済','予約確定通知','予約確定したとき','管理者','新規予約確定のお知らせ（予約番号：#{予約番号}）【RINCLE】','RINCLE運営チーム 各位\n\n以下の内容で新規予約が確定いたしました。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【ご予約内容】\n■予約番号：#{予約番号}\n■貸出予定日時：{貸出日時}\n■返却予定日時：{返却日時}\n■ご利用店舗：{店舗名}\n\n【代表者情報】\n■氏名：{氏名}様\n■電話番号：{電話番号}\n■メールアドレス：{メールアドレス}\n\n【バイク・オプション】\n{バイク情報}\n\n【レンタル料金】\n■合計金額：¥{合計}'],
  [17,'実装済','予約キャンセル通知','予約キャンセルしたとき','管理者','ユーザー予約キャンセル通知【RINCLE】予約番号：#{予約番号}','{店舗名} ご担当者様\n\n下記のご予約がユーザー様によりキャンセルされましたので、ご確認と対応をお願いいたします。\n\n＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝\n【キャンセル内容】\n■予約番号：#{予約番号}\n■キャンセル日：{キャンセル日}\n■ご利用予定日：{貸出日時}\n■返却予定日時：{返却日時}\n■ご利用バイク：{バイク情報}\n\n【レンタル料金】\n■合計金額：¥{合計}'],
  [18,'実装済','お問い合わせ通知','お問い合わせ送信したとき','管理者','（RINCLE_HPお問い合わせ）{種別}','【種別】{種別}\n\n【お名前】{氏名}\n【メール】{メールアドレス}\n\n【お問い合わせ内容】\n{内容}'],
  [19,'協議中','決済失敗アラート','決済失敗したとき','管理者','【RINCLE】決済失敗アラート　予約番号：#{予約番号}','以下の予約で決済に失敗しました。\n\n■予約番号：#{予約番号}\n■ユーザー：{氏名}（{メールアドレス}）\n■店舗：{店舗名}\n■貸出予定日時：{貸出日時}\n■決済金額：¥{合計}\n■エラー内容：{エラー内容}\n\n管理画面で状況を確認してください。'],
];

const DB = [
  [1,'user','____1_text','事業者名',false,false,'text',false,'',''],
  [2,'','name_text','氏名',false,false,'text',false,'',''],
  [3,'','name_kana_text','氏名（カナ）',false,false,'text',false,'',''],
  [4,'','shop_name_text','店舗名',false,false,'text',false,'',''],
  [5,'','shop_address_text','店舗住所',false,false,'text',false,'',''],
  [6,'','shop_access_text','店舗アクセス',false,false,'text',false,'',''],
  [7,'','shop_comment_text','店舗コメント',false,false,'text',false,'',''],
  [8,'','business_hour_text','営業時間',false,false,'text',false,'',''],
  [9,'','address_text','住所',false,false,'text',false,'',''],
  [10,'','contact_mail_text','連絡用メール',false,false,'text',false,'',''],
  [11,'','hp_text','ホームページURL',false,false,'text',false,'',''],
  [12,'','phone_text','電話番号',false,false,'text',false,'',''],
  [13,'','post_number_number','郵便番号',false,false,'number',false,'',''],
  [14,'','birth_date','生年月日',false,false,'date',false,'',''],
  [15,'','last_visit_date','最終訪問日',false,false,'date',false,'',''],
  [16,'','image_image','プロフィール画像',false,false,'image',false,'',''],
  [17,'','cus_id_text','Pay.JP 顧客ID',false,false,'text',false,'',''],
  [18,'','shop_pay_real_text','Pay.JP 公開鍵（本番）',false,false,'text',false,'','⚠️ ハードコードリスク'],
  [19,'','user_id_payjp_text','Pay.JP ユーザーID',false,false,'text',false,'',''],
  [20,'','tenant_id_text','テナントID',false,false,'text',false,'',''],
  [21,'','tall_number','身長',false,false,'number',false,'',''],
  [22,'','_______number','前日貸し出し設定値',false,false,'number',false,'',''],
  [23,'','shop_onboading_boolean','オンボーディング完了',false,false,'boolean',false,'',''],
  [24,'','is____boolean','フラグ①',false,false,'boolean',false,'',''],
  [25,'','cart_custom_____','カート参照',false,false,'ref',false,'','→ ____ (reservation)'],
  [26,'','prefecture_custom_prefecture','都道府県',false,false,'ref',false,'','→ prefecture'],
  [27,'','right_option_rights','アクセス権限',false,false,'option',false,'','rights'],
  [28,'','reviewed_brand_option_brand_status','ブランドレビュー',false,false,'option',false,'','brand_status'],
  [29,'','______list_option______','支払い方法',false,false,'option',true,'','支払いオプションセット'],
  [30,'bicycle','name_text','自転車名',true,false,'text',false,'',''],
  [31,'','brand_name_text','ブランド名',false,false,'text',false,'',''],
  [32,'','color_text','カラー',false,false,'text',false,'',''],
  [33,'','size_text','サイズ',false,false,'text',false,'',''],
  [34,'','serial_number_text','シリアル番号',false,true,'text',false,'',''],
  [35,'','comment_text','コメント',false,false,'text',false,'',''],
  [36,'','no_number','管理番号',false,true,'number',false,'',''],
  [37,'','max_date_number','最大貸出日数',false,false,'number',false,'',''],
  [38,'','ebike_boolean','電動アシスト',false,false,'boolean',false,'',''],
  [39,'','is_archive_boolean','アーカイブ済み',false,false,'boolean',false,'',''],
  [40,'','images_list_image','画像',false,false,'image',true,'',''],
  [41,'','a_hour_price_number','時間単価',false,false,'number',false,'',''],
  [42,'','a_day_price_number','日単価',false,false,'number',false,'',''],
  [43,'','a_week_price_number','週単価',false,false,'number',false,'',''],
  [44,'','a_month_price_number','月単価',false,false,'number',false,'',''],
  [45,'','two_weeks_price_number','2週間単価',false,false,'number',false,'',''],
  [46,'','three_weeks_price_number','3週間単価',false,false,'number',false,'',''],
  [47,'','four_weeks_price_number','4週間単価',false,false,'number',false,'',''],
  [48,'','1_______number','1〜6日単価',false,false,'number',false,'',''],
  [49,'','7__13__number','7〜13日単価',false,false,'number',false,'',''],
  [50,'','14__29__number','14〜29日単価',false,false,'number',false,'',''],
  [51,'','tax_percent_number','税率',false,false,'number',false,'',''],
  [52,'','shop_user','所属ショップ',true,false,'ref',false,'','→ user'],
  [53,'','price_menu_custom_price_menu','料金プラン',false,false,'ref',false,'','→ price_menu'],
  [54,'','bicycle_category_option_bicycle_category','自転車カテゴリ',false,false,'option',false,'','bicycle_category'],
  [55,'price_menu','name_text','プラン名',true,false,'text',false,'',''],
  [56,'','default_boolean','デフォルトフラグ',false,false,'boolean',false,'',''],
  [57,'','for_simulation_boolean','シミュレーション用',false,false,'boolean',false,'',''],
  [58,'','a_hour_price_number','時間単価',false,false,'number',false,'',''],
  [59,'','a_day_price_number','日単価',false,false,'number',false,'',''],
  [60,'','a_week_price_number','週単価',false,false,'number',false,'',''],
  [61,'','a_month_price_number','月単価',false,false,'number',false,'',''],
  [62,'','two_weeks_price_number','2週間単価',false,false,'number',false,'',''],
  [63,'','three_weeks_price_number','3週間単価',false,false,'number',false,'',''],
  [64,'','four_weeks_price_number','4週間単価',false,false,'number',false,'',''],
  [65,'','14____________number','14日〜単価',false,false,'number',false,'',''],
  [66,'','30____________number','30日〜単価',false,false,'number',false,'',''],
  [67,'','_7____________number','7日〜単価',false,false,'number',false,'',''],
  [68,'','more_a_day_price_number','追加日単価',false,false,'number',false,'',''],
  [69,'','more_a_hour_number','追加時間単価',false,false,'number',false,'',''],
  [70,'','tax_percent_number','税率',false,false,'number',false,'',''],
  [71,'','shop_user','所属ショップ',true,false,'ref',false,'','→ user'],
  [72,'option','name_text','オプション名',true,false,'text',false,'',''],
  [73,'','description_text','説明',false,false,'text',false,'',''],
  [74,'','________option__________','難読化オプション',false,false,'option',false,'','__________'],
  [75,'','shop_user','所属ショップ',true,false,'ref',false,'','→ user'],
  [76,'sub_option','name_text','サブオプション名',true,false,'text',false,'',''],
  [77,'','description_text','説明',false,false,'text',false,'',''],
  [78,'','max_number_number','最大数量',false,false,'number',false,'',''],
  [79,'','is_archive_boolean','アーカイブ済み',false,false,'boolean',false,'',''],
  [80,'','a_hour_price_number','時間単価',false,false,'number',false,'',''],
  [81,'','a_day_price_number','日単価',false,false,'number',false,'',''],
  [82,'','a_week_price_number','週単価',false,false,'number',false,'',''],
  [83,'','a_month_price_number','月単価',false,false,'number',false,'',''],
  [84,'','two_weeks_price_number','2週間単価',false,false,'number',false,'',''],
  [85,'','four_weeks_price_number','4週間単価',false,false,'number',false,'',''],
  [86,'','tax_percent_number','税率',false,false,'number',false,'',''],
  [87,'','parent_option_custom_option','親オプション',false,false,'ref',false,'','→ option'],
  [88,'','bicycles_list_custom_bicycle','対応自転車',false,false,'ref',true,'','→ bicycle'],
  [89,'','shop_user','所属ショップ',true,false,'ref',false,'','→ user'],
  [90,'prefecture','name_text','都道府県名',true,false,'text',false,'',''],
  [91,'','index_number','ソート順',false,false,'number',false,'',''],
  [92,'','shop_user','所属ショップ',false,false,'ref',false,'','→ user'],
  [93,'','shoplist_list_user','該当ショップ一覧',false,false,'ref',true,'','→ user'],
  [94,'q_a','title_text','タイトル',true,false,'text',false,'',''],
  [95,'','q_text','質問',true,false,'text',false,'',''],
  [96,'','a_text','回答',true,false,'text',false,'',''],
  [97,'','show_boolean','表示フラグ',false,false,'boolean',false,'',''],
  [98,'','index_number','表示順①',false,false,'number',false,'',''],
  [99,'','index1_number','表示順②',false,false,'number',false,'',''],
  [100,'','category_custom_q_a_category','カテゴリ（参照）',false,false,'ref',false,'','→ q_a_category'],
  [101,'','category_option_q_a_category','カテゴリ（OptionSet）',false,false,'option',false,'','q_a_category'],
  [102,'q_a_category','title_text','カテゴリ名',true,false,'text',false,'',''],
  [103,'','index_number','表示順',false,false,'number',false,'',''],
  [104,'news','title_text','タイトル',true,false,'text',false,'',''],
  [105,'','content_text','本文',false,false,'text',false,'',''],
  [106,'','page_boolean','内部ページフラグ',false,false,'boolean',false,'',''],
  [107,'','page_content_text','内部ページコンテンツ',false,false,'text',false,'',''],
  [108,'','external_url_text','外部URL',false,false,'text',false,'',''],
  [109,'','rights_option_rights','表示権限',false,false,'option',false,'','rights'],
  [110,'banner','title_text','タイトル',true,false,'text',false,'',''],
  [111,'','content_text','説明文',false,false,'text',false,'',''],
  [112,'','external_url_text','外部URL',false,false,'text',false,'',''],
  [113,'','image_image','バナー画像',false,false,'image',false,'',''],
  [114,'','page_boolean','内部ページフラグ',false,false,'boolean',false,'',''],
  [115,'','page_content_text','内部ページコンテンツ',false,false,'text',false,'',''],
  [116,'fv','title_text','タイトル',true,false,'text',false,'',''],
  [117,'','external_url_text','外部URL',false,false,'text',false,'',''],
  [118,'','image_image','画像',false,false,'image',false,'',''],
  [119,'','page_boolean','内部ページフラグ',false,false,'boolean',false,'',''],
  [120,'','page_content_text','内部ページコンテンツ',false,false,'text',false,'',''],
  [121,'holidays','date_date','日付',true,false,'date',false,'',''],
  [122,'access_log','date_date','アクセス日時',true,false,'date',false,'',''],
  [123,'','ip_text','IPアドレス',false,false,'text',false,'',''],
  [124,'webhook_event','text_text','イベント本文',false,false,'text',false,'',''],
  [125,'','type_text','イベント種別',false,false,'text',false,'',''],
  [126,'____ (reservation)','____1_number','予約番号',false,true,'number',false,'',''],
  [127,'','____date','貸出日',true,false,'date',false,'',''],
  [128,'','___1_date','返却日',true,false,'date',false,'',''],
  [129,'','_____number','合計金額',false,false,'number',false,'',''],
  [130,'','____2_number','延長料金',false,false,'number',false,'',''],
  [131,'','charge_id_text','Pay.JP チャージID',false,false,'text',false,'',''],
  [132,'','__charge_id_text','Pay.JP チャージID②',false,false,'text',false,'',''],
  [133,'','token_text','決済トークン',false,false,'text',false,'',''],
  [134,'','_______boolean','ステータス①',false,false,'boolean',false,'',''],
  [135,'','________boolean','ステータス②',false,false,'boolean',false,'',''],
  [136,'','_____boolean','ステータス③',false,false,'boolean',false,'',''],
  [137,'','___user','ユーザー',true,false,'ref',false,'','→ user'],
  [138,'','________list_custom_______1','予約明細リスト',false,false,'ref',true,'','→ _______1 (reservation_detail)'],
  [139,'','__________list_custom__________1','オプション価格リスト',false,false,'ref',true,'','→ _________1 (option_price)'],
  [140,'','________option___yesno','Yes/No選択',false,false,'option',false,'','__yesno'],
  [141,'_____ (booking_customer)','name_text','氏名',false,false,'text',false,'',''],
  [142,'','name_kana_text','氏名（カナ）',false,false,'text',false,'',''],
  [143,'','email_text','メールアドレス',false,false,'text',false,'',''],
  [144,'','phone_text_text','電話番号',false,false,'text',false,'',''],
  [145,'','address_text','住所',false,false,'text',false,'',''],
  [146,'','signup_user_boolean','会員登録フラグ',false,false,'boolean',false,'',''],
  [147,'','_____number','数値②',false,false,'number',false,'',''],
  [148,'','_____date','日付',false,false,'date',false,'',''],
  [149,'_______1 (reservation_detail)','____date','貸出日',true,false,'date',false,'',''],
  [150,'','___1_date','返却日',true,false,'date',false,'',''],
  [151,'','_____number','合計金額',false,false,'number',false,'',''],
  [152,'','____1_number','金額①',false,false,'number',false,'',''],
  [153,'','____2_number','金額②',false,false,'number',false,'',''],
  [154,'','____custom_bicycle','自転車',true,false,'ref',false,'','→ bicycle'],
  [155,'','price_menu_custom_price_menu','料金プラン',false,false,'ref',false,'','→ price_menu'],
  [156,'','______custom______','予約参照',false,false,'ref',false,'','→ ____ (reservation)'],
  [157,'','_____custom_____','顧客情報参照',false,false,'ref',false,'','→ _____ (booking_customer)'],
  [158,'','__________list_custom__________1','オプション価格リスト',false,false,'ref',true,'','→ _________1 (option_price)'],
  [159,'','___user','ユーザー',false,false,'ref',false,'','→ user'],
  [160,'_________1 (option_price)','___number','金額',false,false,'number',false,'',''],
  [161,'','price_menu_custom_price_menu','料金プラン',false,false,'ref',false,'','→ price_menu'],
  [162,'','______custom_sub_option','サブオプション',false,false,'ref',false,'','→ sub_option'],
  [163,'_______ (shop_schedule)','___date','対象日',true,false,'date',false,'',''],
  [164,'','starttime_option_time','開始時間',false,false,'option',false,'','time'],
  [165,'','endtime_option_time','終了時間',false,false,'option',false,'','time'],
  [166,'','____user','所属ショップ',true,false,'ref',false,'','→ user'],
  [167,'','_____option_____op','スケジュール区分',false,false,'option',false,'','____op'],
  [168,'','__________s_list_custom_bicycle','対象自転車リスト',false,false,'ref',true,'','→ bicycle'],
  [169,'___________ (business_hours)','startdate_date','開始日',true,false,'date',false,'',''],
  [170,'','enddate_date','終了日',true,false,'date',false,'',''],
  [171,'','starttime_option_time','開始時間',false,false,'option',false,'','time'],
  [172,'','endtime_option_time','終了時間',false,false,'option',false,'','time'],
  [173,'','____user','所属ショップ',true,false,'ref',false,'','→ user'],
  [174,'','_____option_____op','スケジュール区分',false,false,'option',false,'','____op'],
  [175,'','___option___','曜日区分',false,false,'option',false,'','__（曜日）'],
  [176,'','___boolean','フラグ',false,false,'boolean',false,'',''],
  [177,'______ (sales_record)','date_date','記録日',true,false,'date',false,'',''],
  [178,'','__number','金額①',false,false,'number',false,'',''],
  [179,'','_1_number','金額②',false,false,'number',false,'',''],
  [180,'','____number','金額③',false,false,'number',false,'',''],
  [181,'','___boolean','処理済みフラグ',false,false,'boolean',false,'',''],
  [182,'','shop_user','所属ショップ',true,false,'ref',false,'','→ user'],
  [183,'_______news (shop_notification)','viewed_boolean','既読フラグ',false,false,'boolean',false,'',''],
  [184,'','shop_user','所属ショップ',true,false,'ref',false,'','→ user'],
  [185,'','right_option_rights','表示権限',false,false,'option',false,'','rights'],
  [186,'','news_type_option________news_type','通知種別',false,false,'option',false,'','_______news_type'],
  [187,'________1 (contact_inquiry)','__1_text','氏名',false,false,'text',false,'',''],
  [188,'','___text','メールアドレス',false,false,'text',false,'',''],
  [189,'','________text','本文',false,false,'text',false,'',''],
  [190,'','______boolean','対応済みフラグ',false,false,'boolean',false,'',''],
  [191,'','_____user','ユーザー参照',false,false,'ref',false,'','→ user'],
  [192,'________ (ip_rights)','___text','IPアドレス等',false,false,'text',false,'',''],
  [193,'','____option_rights','アクセス権限',false,false,'option',false,'','rights'],
  [194,'______defaults','date_date','日付',true,false,'date',false,'',''],
  [195,'','holiday_boolean','祝日フラグ',false,false,'boolean',false,'',''],
  [196,'_________ (holiday_master)','date_date','日付',true,false,'date',false,'',''],
  [197,'','hliday_boolean','祝日フラグ',false,false,'boolean',false,'','typo: holiday'],
  [198,'______1 (reservation_count)','number_number','数値',false,false,'number',false,'',''],
];

function esc(s) { return String(s ?? '').replace(/'/g, "''"); }
function bool(v) { return v ? 'true' : 'false'; }

let sql = '-- ── screens ──────────────────────────────────────────────────────\n';
// screens: [id, item, component, feature, improvement, path]  (6 cols, no detail)
sql += 'insert into screens (sort_order, screen_id, item, component, feature, detail, improvement, path) values\n';
sql += SCREENS.map((r, i) =>
  `(${i}, '${esc(r[0])}', '${esc(r[1])}', '${esc(r[2])}', '${esc(r[3])}', '', '${esc(r[4])}', '${esc(r[5])}')`
).join(',\n') + ';\n\n';

sql += '-- ── emails ──────────────────────────────────────────────────────\n';
sql += 'insert into emails (sort_order, no, status, name, timing, recipient, subject, body) values\n';
sql += EMAILS.map((r, i) =>
  `(${i}, '${esc(r[0])}', '${esc(r[1])}', '${esc(r[2])}', '${esc(r[3])}', '${esc(r[4])}', '${esc(r[5])}', '${esc(r[6])}')`
).join(',\n') + ';\n\n';

sql += '-- ── db_fields ────────────────────────────────────────────────────\n';
sql += 'insert into db_fields (sort_order, field_id, table_name, field_name, display_name, required, ix, dtype, list, validation, notes) values\n';
sql += DB.map((r, i) =>
  `(${i}, '${esc(r[0])}', '${esc(r[1])}', '${esc(r[2])}', '${esc(r[3])}', ${bool(r[4])}, ${bool(r[5])}, '${esc(r[6])}', ${bool(r[7])}, '${esc(r[8])}', '${esc(r[9])}')`
).join(',\n') + ';\n';

import { writeFileSync } from 'fs';
writeFileSync('scripts/seed.sql', sql);
console.log('✓ scripts/seed.sql を生成しました');
